spring:
  profile:
      active:
      - dev
---
spring:
  profile: dev
  application: 
      name: microservicecloud-config-autiguigu-dev
---
spring:
  profile: test
  application: 
      name: microservicecloud-config-autiguigu-test